### ISSUE TITLE
[OFFTOP] Scrum Planning pull request - saving the kind of cards

### ISSUE THREAD

**Issue by franpog859** [caioedut/phphtml#1]
Hey, @caioedut! I use your Scrum Planning app and there was a link to your GitHub account. Is this app open source somewhere? 
I think it will be a great feature to store in some sort of user state the fact which kind of cards user was using in previous session. App would start with this kind selected and user would not have to change it everytime.
I tried to find it here on GitHub to create a pull request but it appears not to be open. Will you consider that?

**Comment by caioedut** [comment]
It's a great idea, I'll put it as soon as possible.
Soon as well I'll share the app code.

Thank you.

**Comment by caioedut** [comment]
Added on beta version :)
